id: P002912
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:57.826560
source_metadata:
  id: bdr:W21611
  title: དབུས་གཙང་གི་གནས་ཡིག
  author: ''
  volumes:
    3765b53bab214578969d4c0fe53c04e4:
      image_group_id: I5691
      title: ''
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
